### ISSUE TITLE
Error loading rviz config.

### ISSUE THREAD

**Issue by ziyangli** [rpng/cpi#1]
`[ERROR] [1529551374.105377990]: PluginlibFactory: The plugin for class 'rviz/PoseWithCovariance' failed to load.  Error: According to the loaded plugin descriptions the class rviz/PoseWithCovariance with base class type rviz::Display does not exist. Declared types are  rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/WrenchStamped rviz_imu_plugin/Imu rviz_plugin_covariance/OdometryWithCovariance rviz_plugin_covariance/PoseWithCovariance`

My system is ubuntu14.04 and there is no such a rviz plugin.

**Comment by goldbattle** [comment]
What version of ROS are you using?
That should be a standard RVIZ display type.

**Comment by ziyangli** [comment]
Indigo.

I start rviz with an empty config and manually load all the topics(3 imu poses, 3 imu pathes, 3 point clounds, etc) then everything is fine.
